FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get upgrade
RUN apt-get install -y git ca-certificates && update-ca-certificates
RUN apt-get -y install golang-go

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
COPY *.go ./

RUN go mod download && go get .
RUN go build -o /albums

EXPOSE 8080

ENTRYPOINT [ "/albums" ]