## build stage
FROM golang:1.16-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
COPY *.go ./

RUN go mod download && go get .
RUN go build -o /albums

## Deploy stage

FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=build /albums /albums

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT [ "/albums" ]